# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 297a31255ae67241b5384a1f1ab582791509437c3ca8c1cab192c26ae1c85fd9dd4f171c38240a39a6cfbe132ce30a7593a6ff8e6bf9946d94f2fb55023c0aa6

test:
  secret_key_base: 56d726e62c0d19f04a37666f1cb68af20a7a855851ca0b1880f6f94d7643ebf084b97e3ef99651465c27beb79d64f7709f4b8d63294edca321be756d281da189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
